package Interface;

import com.mycompany.trabajofinal1.Cita;
import com.mycompany.trabajofinal1.Paciente;
import javax.swing.JOptionPane;
import com.mycompany.trabajofinal1.Empleado;
import com.mycompany.trabajofinal1.Medico;
import java.awt.Component;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JList;
import javax.swing.JTextPane;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import javax.swing.text.StyledEditorKit;

/**
 *
 * @author SEBASTIAN MORENO
 * @id: 1192792720
 * @fecha: 25/noviembre/2023
 *
 */

public class CitaInterface extends javax.swing.JFrame {

    public Paciente pacienteCita;

    /**
     * Creates new form Cita
     */
    public CitaInterface() {
        initComponents();
        jTextPaneDatosPaciente.setEditorKit(new StyledEditorKit());
        jTextPaneDatosPaciente.putClientProperty(JTextPane.W3C_LENGTH_UNITS, true);
        StyledDocument doc = jTextPaneDatosPaciente.getStyledDocument();
        SimpleAttributeSet centerAligment = new SimpleAttributeSet();
        StyleConstants.setAlignment(centerAligment, StyleConstants.ALIGN_CENTER);
        doc.setParagraphAttributes(0, doc.getLength(), centerAligment, false);
        loadData();
        jTextAreaMedico.setLineWrap(true);
        jTextAreaMedico.setAlignmentX(Component.CENTER_ALIGNMENT);
        jTextAreaMedico.setFont(new Font("Monospaced", Font.PLAIN, 14));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabelMedico = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaMedico = new javax.swing.JTextArea();
        jLabelVlrCita = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPaneVlrCita = new javax.swing.JTextPane();
        jButtonSaveCita = new javax.swing.JButton();
        jButtonCloseCita = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldDocumentoPaciente = new javax.swing.JTextField();
        jDateChooserCita = new com.toedter.calendar.JDateChooser();
        jButtonFind = new javax.swing.JButton();
        jComboBoxMedicoCita = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneDatosPaciente = new javax.swing.JTextPane();
        jLabelFecha = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelHora = new javax.swing.JLabel();
        timePickerCita = new com.github.lgooddatepicker.components.TimePicker();
        jLabelConsultorio = new javax.swing.JLabel();
        jButtonNewCita = new javax.swing.JButton();
        jComboBoxConsultorio = new javax.swing.JComboBox<>();
        jLabelDatosPaciente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Crear Paciente");
        jButton1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButton1.setPreferredSize(new java.awt.Dimension(88, 23));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 610, 127, 37));

        jLabel7.setText("AGENDAR");
        jLabel7.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        jLabelMedico.setText("Medico");
        jLabelMedico.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabelMedico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabelMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, -1, -1));

        jTextAreaMedico.setColumns(20);
        jTextAreaMedico.setEditable(false);
        jTextAreaMedico.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jTextAreaMedico.setRows(5);
        jTextAreaMedico.setAlignmentX(0.0F);
        jTextAreaMedico.setAlignmentY(0.0F);
        jTextAreaMedico.setBackground(new java.awt.Color(255, 255, 255));
        jTextAreaMedico.setFocusable(false);
        jScrollPane2.setViewportView(jTextAreaMedico);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 470, 126));

        jLabelVlrCita.setText("Valor Consulta");
        jLabelVlrCita.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jPanel1.add(jLabelVlrCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 570, -1, -1));

        jTextPaneVlrCita.setEditable(false);
        jTextPaneVlrCita.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jTextPaneVlrCita.setBackground(new java.awt.Color(255, 255, 255));
        jTextPaneVlrCita.setCaretColor(new java.awt.Color(102, 102, 255));
        jTextPaneVlrCita.setFocusable(false);
        jScrollPane3.setViewportView(jTextPaneVlrCita);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 570, 152, -1));

        jButtonSaveCita.setText("Agendar Cita");
        jButtonSaveCita.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButtonSaveCita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSaveCitaMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonSaveCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 610, -1, 37));

        jButtonCloseCita.setText("Cerrar");
        jButtonCloseCita.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButtonCloseCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseCitaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCloseCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, 94, 37));

        jLabel4.setText("CITA MEDICA");
        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\SEBASTIAN MORENO\\Downloads\\agenda.png")); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, 108));

        jLabel6.setText("Documento Paciente");
        jLabel6.setAlignmentY(0.0F);
        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, -1));

        jTextFieldDocumentoPaciente.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jPanel1.add(jTextFieldDocumentoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 180, 29));
        jPanel1.add(jDateChooserCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 158, -1));

        jButtonFind.setIcon(new javax.swing.ImageIcon("C:\\Users\\SEBASTIAN MORENO\\Downloads\\find.png")); // NOI18N
        jButtonFind.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonFindMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 50, 50));

        jComboBoxMedicoCita.setAlignmentX(0.0F);
        jComboBoxMedicoCita.setAlignmentY(0.0F);
        jPanel1.add(jComboBoxMedicoCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 144, 26));

        jTextPaneDatosPaciente.setEditable(false);
        jTextPaneDatosPaciente.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jTextPaneDatosPaciente.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTextPaneDatosPaciente);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 417, 77));

        jLabelFecha.setText("Fecha de la Consulta");
        jLabelFecha.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jPanel1.add(jLabelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        jLabel1.setText("Datos de la Cita Agendada");
        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, -1, -1));

        jLabelHora.setText("Hora Consulta");
        jLabelHora.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jPanel1.add(jLabelHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));
        jPanel1.add(timePickerCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 158, -1));

        jLabelConsultorio.setText("Consultorio");
        jLabelConsultorio.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jPanel1.add(jLabelConsultorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, -1));

        jButtonNewCita.setText("Nueva Cita");
        jButtonNewCita.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButtonNewCita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNewCitaMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonNewCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 610, 100, 37));

        jComboBoxConsultorio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----", "C1", "C2", "C3", "C4", "C5" }));
        jPanel1.add(jComboBoxConsultorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, -1, 26));

        jLabelDatosPaciente.setText("Datos Paciente");
        jLabelDatosPaciente.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLabelDatosPaciente.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jPanel1.add(jLabelDatosPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCloseCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseCitaActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCloseCitaActionPerformed

    private void jButtonSaveCitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSaveCitaMouseClicked
        if (jTextFieldDocumentoPaciente.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Ingrese una Identificacion");
            return;
        }

        if (jDateChooserCita.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Ingrese la Fecha de la consulta");
            return;
        }

        if (timePickerCita.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Ingresa una Hora para su Consulta");
            return;
        }

        if (jComboBoxConsultorio.getSelectedItem().toString().startsWith("---")) {
            JOptionPane.showMessageDialog(null, "Seleccione un Consultorio");
            return;
        }

        if (jComboBoxMedicoCita.getSelectedItem().toString().startsWith("---")) {
            JOptionPane.showMessageDialog(null, "Seleccione un Medico");
            return;
        }

        if (jTextFieldDocumentoPaciente.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Ingrese una Identificacion");
            return;
        } else {
            String datosCita = "Nombre del Paciente:" + pacienteCita.getNombre() + "\n" + "Identificacion: " + pacienteCita.getDireccion()
                    + "\n" + "Fecha Cita: " + fechaToString(jDateChooserCita.getDate()) + "\n" + "Hora Cita:" + timePickerCita.getText();

            jTextAreaMedico.setText(datosCita);
        }

        try {
            int id = Integer.parseInt(jTextFieldDocumentoPaciente.getText());
            if (id > 999999999) {
                JOptionPane.showMessageDialog(null, "Identificacion no Valida");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingrese un valor numerico valido en Identificacion");
            return;
        }

        Cita objCita = new Cita();
        objCita.setPaciente(this.pacienteCita);
        objCita.setConsultorio(jComboBoxConsultorio.getSelectedItem().toString());
        objCita.setFecha(fechaToString(jDateChooserCita.getDate()));
        objCita.setHora(timePickerCita.getText());
        objCita.setConsultorio(jComboBoxConsultorio.getSelectedItem().toString());
        Medico objMedico = new Medico();
        objMedico.setNombre(jComboBoxMedicoCita.getSelectedItem().toString());
        objCita.setMedico(objMedico);
        objCita.setValorCita(Double.parseDouble(jTextPaneVlrCita.getText()));
        objCita.setMedicoNombre(jComboBoxMedicoCita.getSelectedItem().toString());

        if (objCita.existeCitaPaciente(objCita)) {
            JOptionPane.showMessageDialog(null, "El Paciente tiene una cita agendada para ese dia");
            return;
        }
        
        if(objCita.existeMedicoDisponible(objCita)){
            JOptionPane.showMessageDialog(null, "El medico no esta disponible en esa hora y fecha");
            return;
        }
        
        if (objCita.almacenarDatosCita(objCita)) {
            JOptionPane.showMessageDialog(null, "La Cita fue Guardado");

        }


    }//GEN-LAST:event_jButtonSaveCitaMouseClicked

    public void ClearScreen() {
        jTextFieldDocumentoPaciente.setText("");
        jTextPaneDatosPaciente.setText("");
        jDateChooserCita.setDate(null);
        timePickerCita.setTime(null);
        jComboBoxConsultorio.setSelectedItem(0);
        jComboBoxMedicoCita.setSelectedItem(null);
        jTextAreaMedico.setText("");
        jTextPaneVlrCita.setText("");
        jComboBoxConsultorio.setSelectedItem(null);
    }

    public String fechaToString(Date fechaDate) {
        
        SimpleDateFormat fechaok = new SimpleDateFormat("dd/MM/yyyy");
        String fechaFormat = fechaok.format(fechaDate);
        
        return fechaFormat;
    }

    private void jButtonFindMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFindMouseClicked
        if (jTextFieldDocumentoPaciente.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Ingrese una Identificacion");
            return;
        }

        try {
            int id = Integer.parseInt(jTextFieldDocumentoPaciente.getText());
            if (id > 999999999) {
                JOptionPane.showMessageDialog(null, "Identificacion no Valida");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingrese un valor numerico valido en Identificacion");
            return;
        }

        Paciente objPaciente = new Paciente();
        objPaciente = objPaciente.getPacientexId(Integer.parseInt(jTextFieldDocumentoPaciente.getText()));

        if (objPaciente != null) {
            String datosPaciente = "Nombre:" + objPaciente.getNombre() + "\n" + "Direccion: " + objPaciente.getDireccion() + "\n" + "Edad: " + objPaciente.getEdad();
            pacienteCita = objPaciente;
            jTextPaneDatosPaciente.setText(datosPaciente);

        } else {
            JOptionPane.showMessageDialog(null, "El paciente no existe");
            jTextFieldDocumentoPaciente.setText("");
            jTextPaneDatosPaciente.setFocusable(rootPaneCheckingEnabled);
        }

        jTextPaneVlrCita.setText(Double.toString(objPaciente.pagoConsulta()));


    }//GEN-LAST:event_jButtonFindMouseClicked

    private void jButtonNewCitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNewCitaMouseClicked
        ClearScreen();

        if (jTextPaneDatosPaciente.getText().isBlank()) {
            jTextFieldDocumentoPaciente.grabFocus();
            return;
        } else {
            JOptionPane.showMessageDialog(null, "Error de focus en un jtextpanedocumentoPaciente");
            return;
        }


    }//GEN-LAST:event_jButtonNewCitaMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        PacienteInterface formPacienteInterface = new PacienteInterface();
        
        formPacienteInterface.show();
    }//GEN-LAST:event_jButton1MouseClicked

    private void loadData() {
        List<Empleado> listaMedicos = new ArrayList<>();
        Empleado objEmpleado = new Empleado();
        listaMedicos = objEmpleado.getMedicos();

        DefaultComboBoxModel<String> defaultComboBoxModel = new DefaultComboBoxModel<String>();
        defaultComboBoxModel.addElement("---------------------------------");
        for (Empleado empleado : listaMedicos) {
            defaultComboBoxModel.addElement(empleado.getNombre());
        }

        jComboBoxMedicoCita.setModel(defaultComboBoxModel);
        jComboBoxMedicoCita.setRenderer(new MedicoListCellRender());

    }

    
    
    private class MedicoListCellRender extends DefaultListCellRenderer {

        @Override
        public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
            if (value instanceof Empleado) {
                Empleado objEmpleado = (Empleado) value;
                //value = objEmpleado.getNombre();}
                value = ((Empleado) value).getNombre();

            }
            return super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CitaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CitaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CitaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CitaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CitaInterface().setVisible(true);
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCloseCita;
    private javax.swing.JButton jButtonFind;
    private javax.swing.JButton jButtonNewCita;
    private javax.swing.JButton jButtonSaveCita;
    private javax.swing.JComboBox<String> jComboBoxConsultorio;
    private javax.swing.JComboBox<String> jComboBoxMedicoCita;
    private com.toedter.calendar.JDateChooser jDateChooserCita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelConsultorio;
    private javax.swing.JLabel jLabelDatosPaciente;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelMedico;
    private javax.swing.JLabel jLabelVlrCita;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaMedico;
    private javax.swing.JTextField jTextFieldDocumentoPaciente;
    private javax.swing.JTextPane jTextPaneDatosPaciente;
    private javax.swing.JTextPane jTextPaneVlrCita;
    private com.github.lgooddatepicker.components.TimePicker timePickerCita;
    // End of variables declaration//GEN-END:variables

}
