package Interface;

import Datos.CrearDatos;
import com.google.gson.Gson;
import com.mycompany.trabajofinal1.Cita;
import com.mycompany.trabajofinal1.ConsultaMedica;
import com.mycompany.trabajofinal1.Medico;
import com.mycompany.trabajofinal1.Paciente;
import java.awt.event.ItemEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import com.mycompany.trabajofinal1.Diagnostico;
import java.awt.Component;
import java.awt.Font;

/**
 *
 * @author SEBASTIAN MORENO
 * @id: 1192792720
 * @fecha: 25/noviembre/2023
 *
 */

public class ConsultaMedicaInterface extends javax.swing.JFrame {

    public Paciente objPaciente;
    public ConsultaMedica consultaMedica;

    /**
     * Creates new form ConsultaMedicaInterface
     */
    public ConsultaMedicaInterface() {
        initComponents();

        Date fechaActual = new Date();
        jTextFieldFechaMostrar.setText(fechaToString(fechaActual));

        for (String diagnostico : Diagnostico.getDiagnosticos()) {
            jComboBoxDiagnostico.addItem(diagnostico);
        }

        jTextAreaTratamiento.setLineWrap(true);
        jTextAreaTratamiento.setAlignmentX(Component.CENTER_ALIGNMENT);
        jTextAreaTratamiento.setFont(new Font("Monospaced", Font.PLAIN, 14));
        jComboBoxDiagnostico.addItemListener(this::jComboBoxDiagnosticoItemStateChanged);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldPaciente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldidFind = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaTratamiento = new javax.swing.JTextArea();
        jButtonFind = new javax.swing.JButton();
        jButtonNewConsulta = new javax.swing.JButton();
        jButtonCloseConsulta = new javax.swing.JButton();
        jButtonSaveConsulta = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxDiagnostico = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldFechaMostrar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldMedico = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldPaciente.setEditable(false);
        jTextFieldPaciente.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldPaciente.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jTextFieldPaciente.setToolTipText("Nombre paciente");
        jPanel1.add(jTextFieldPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 180, 220, 30));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel5.setText("Tratamiento");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel8.setText("BUSQUEDA CON IDENTIFICACION");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel6.setText("Paciente");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, -1, -1));

        jTextFieldidFind.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jTextFieldidFind.setToolTipText("Ingresa identificacion");
        jPanel1.add(jTextFieldidFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 210, -1));

        jTextAreaTratamiento.setEditable(false);
        jTextAreaTratamiento.setColumns(20);
        jTextAreaTratamiento.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jTextAreaTratamiento.setRows(5);
        jTextAreaTratamiento.setToolTipText("Tratamiento para su diagnostico");
        jScrollPane2.setViewportView(jTextAreaTratamiento);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 460, 150));

        jButtonFind.setIcon(new javax.swing.ImageIcon("C:\\Users\\SEBASTIAN MORENO\\Downloads\\find2.png")); // NOI18N
        jButtonFind.setToolTipText("Busqueda de cita");
        jButtonFind.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonFindMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, -1, -1));

        jButtonNewConsulta.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButtonNewConsulta.setText("Nueva Consulta");
        jButtonNewConsulta.setToolTipText("Realizar una nueva consulta medica");
        jButtonNewConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNewConsultaMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonNewConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 188, 30));

        jButtonCloseConsulta.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButtonCloseConsulta.setText("Cerrar");
        jButtonCloseConsulta.setToolTipText("Cerrar ventana consulta");
        jButtonCloseConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCloseConsultaMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonCloseConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 500, 85, 30));

        jButtonSaveConsulta.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButtonSaveConsulta.setText("Guardar");
        jButtonSaveConsulta.setToolTipText("Guardar datos del diagnostico y tratamiento");
        jButtonSaveConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSaveConsultaMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonSaveConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, 85, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\SEBASTIAN MORENO\\Downloads\\Agenda_1.png")); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel1.setText("CONSULTA MEDICA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        jComboBoxDiagnostico.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jComboBoxDiagnostico.setToolTipText("Selecciona un diagnostico");
        jComboBoxDiagnostico.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxDiagnosticoItemStateChanged(evt);
            }
        });
        jPanel1.add(jComboBoxDiagnostico, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 270, 35));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel2.setText("Fecha");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        jTextFieldFechaMostrar.setEditable(false);
        jTextFieldFechaMostrar.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldFechaMostrar.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jTextFieldFechaMostrar.setToolTipText("Fecha consulta atendida");
        jPanel1.add(jTextFieldFechaMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 111, 30));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel3.setText("Medico");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, -1));

        jTextFieldMedico.setEditable(false);
        jTextFieldMedico.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldMedico.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jTextFieldMedico.setToolTipText("Nombre medico");
        jPanel1.add(jTextFieldMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 150, 30));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel4.setText("Diagnostico");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCloseConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCloseConsultaMouseClicked
        this.dispose();
    }//GEN-LAST:event_jButtonCloseConsultaMouseClicked

    private void jButtonFindMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFindMouseClicked
        if (jTextFieldidFind.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Ingrese Una Identificacion");
            return;
        }
        try {
            int id = Integer.parseInt(jTextFieldidFind.getText());
            if (id > 999999999) {
                JOptionPane.showMessageDialog(null, "Identificacion No Valida");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingrese Un Valor Numerico Valido En La Identificacion");
            return;
        }

        Cita objcita = new Cita();
        objcita = objcita.getCitaxId(Integer.parseInt(jTextFieldidFind.getText()));

        if (objcita == null) {
            JOptionPane.showMessageDialog(null, "Paciente No tiene cita");
            return;
        } else {

            jTextFieldPaciente.setText(objcita.getPaciente().getNombre());
            jTextFieldMedico.setText(objcita.getMedicoNombre());
        }

    }//GEN-LAST:event_jButtonFindMouseClicked

    private void jComboBoxDiagnosticoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxDiagnosticoItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            String diagnosticoSeleccionado = (String) jComboBoxDiagnostico.getSelectedItem();

            String tratamientoDiag = obtenerTratamiento(diagnosticoSeleccionado);

            jTextAreaTratamiento.setText(tratamientoDiag);
        }

    }//GEN-LAST:event_jComboBoxDiagnosticoItemStateChanged

    private void jButtonNewConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNewConsultaMouseClicked
        clearScreen();
    }//GEN-LAST:event_jButtonNewConsultaMouseClicked

    private void jButtonSaveConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSaveConsultaMouseClicked
        if (jTextFieldidFind.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Ingrese Una Identificacion");
        }
        try {
            int id = Integer.parseInt(jTextFieldidFind.getText());
            if (id > 999999999) {
                JOptionPane.showMessageDialog(null, "Identificacion No Valida");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingrese Un Valor Numerico Valido En La Identificacion");
            return;
        }

        if (jComboBoxDiagnostico.getSelectedItem().toString().startsWith("-----")) {
            JOptionPane.showMessageDialog(null, "Ingrese una Opcion de Diagnostico");
            return;
        }
        
        //revisar lo de guardar los datos en el archivo
        ConsultaMedica objConsultaMedica = new ConsultaMedica();
        
        Paciente paciente = new Paciente();
        paciente = paciente.getPacientexId(Integer.parseInt(jTextFieldidFind.getText()));
        
        if (paciente != null) {

            objConsultaMedica.setNombrePaciente(paciente.getNombre());
        } else {

            JOptionPane.showMessageDialog(null, "Paciente no encontrado para la consulta.");
            return;
        }
        Medico medico = new Medico();
        medico = medico.getMedicobyName(jTextFieldMedico.getText());
        objConsultaMedica.setPaciente(paciente);
        objConsultaMedica.setFecha(jTextFieldFechaMostrar.getText());
        objConsultaMedica.setMedico(medico);
        objConsultaMedica.setDiagnostico((jComboBoxDiagnostico.getSelectedItem().toString()));
        objConsultaMedica.setTratamiento(jTextAreaTratamiento.getText());
        
        if (objConsultaMedica.almacenarDatosConsulta(objConsultaMedica)) {
            JOptionPane.showMessageDialog(null, "La Consulta fue Guardada");
            clearScreen();
        }

        

    }//GEN-LAST:event_jButtonSaveConsultaMouseClicked

    public void clearScreen() {
        jTextFieldidFind.setText("");
        jTextFieldMedico.setText("");
        jTextFieldPaciente.setText("");
        jComboBoxDiagnostico.setSelectedItem(null);
        jTextAreaTratamiento.setText("");
    }

    public String obtenerTratamiento(String diagnostico) {
        int index = Diagnostico.getDiagnosticos().indexOf(diagnostico);

        if (index != -1) {
            return Diagnostico.getTratamientos().get(index);
        } else {
            return "Tratamiento no encontrado para el diagnostico: " + diagnostico;
        }
    }

    public boolean existePaciente(int sIdentificacion) {//para todos

        for (Paciente objPaciente : getPacientes()) {
            if (objPaciente.getIdentifiacion() == sIdentificacion) {
                return true;
            }
        }
        return false;

    }

    public List<Paciente> getPacientes() {//leer los datos y convertirlos en list para todos

        CrearDatos archivo = new CrearDatos("Pacientes.txt");

        List<String> listaPacientes = archivo.leerArchivo();
        String sPaciente;

        List<Paciente> listaJsonPacientes = new ArrayList<>();
        for (String item : listaPacientes) {
            Gson gson = new Gson();
            Paciente objPaciente = gson.fromJson(item, Paciente.class);
            listaJsonPacientes.add(objPaciente);

        }
        return listaJsonPacientes;

    }

    public String fechaToString(Date fechaDate) {

        SimpleDateFormat fechaok = new SimpleDateFormat("dd/MM/yyyy");
        String fechaFormat = fechaok.format(fechaDate);

        return fechaFormat;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaMedicaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaMedicaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaMedicaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaMedicaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ConsultaMedicaInterface().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCloseConsulta;
    private javax.swing.JButton jButtonFind;
    private javax.swing.JButton jButtonNewConsulta;
    private javax.swing.JButton jButtonSaveConsulta;
    private javax.swing.JComboBox<String> jComboBoxDiagnostico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaTratamiento;
    private javax.swing.JTextField jTextFieldFechaMostrar;
    private javax.swing.JTextField jTextFieldMedico;
    private javax.swing.JTextField jTextFieldPaciente;
    private javax.swing.JTextField jTextFieldidFind;
    // End of variables declaration//GEN-END:variables
}
