package Interface;

import com.mycompany.trabajofinal1.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.SimpleFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author SEBASTIAN MORENO
 * @id: 1192792720
 * @fecha: 25/noviembre/2023
 *
 */

public class EmpleadoInterface extends javax.swing.JFrame {

    /**
     * Creates new form Empleado
     */
    public EmpleadoInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldJefe = new javax.swing.JTextField();
        JTextNombreEmpleado = new javax.swing.JTextField();
        jButtonCloseEmpleado = new javax.swing.JButton();
        jLabelCargo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxCargo = new javax.swing.JComboBox<>();
        jComboBoxGenero = new javax.swing.JComboBox<>();
        jButtonSaveEmpleado = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabelSalario = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldSalario = new javax.swing.JTextField();
        jDateChooserEmpleado = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jTextFieldEdad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jLabel4.setText("NOMBRE DEL JEFE");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jLabel1.setText("NOMBRE Y APELLIDOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jTextFieldJefe.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jPanel1.add(jTextFieldJefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 192, -1));

        JTextNombreEmpleado.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jPanel1.add(JTextNombreEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 192, -1));

        jButtonCloseEmpleado.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButtonCloseEmpleado.setText("CERRAR");
        jButtonCloseEmpleado.setToolTipText("Cerrar ventana");
        jButtonCloseEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCloseEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 87, 35));

        jLabelCargo.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jLabelCargo.setText("CARGO");
        jPanel1.add(jLabelCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jLabel5.setText("GENERO");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        jComboBoxCargo.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jComboBoxCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------------", "Medico", "Enfermera", "Auxiliares de enfermeria", "Enfermeros jefes", "Paramédicos" }));
        jComboBoxCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCargoActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 118, -1));

        jComboBoxGenero.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jComboBoxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----------", "Masculino", "Femenino" }));
        jComboBoxGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGeneroActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));

        jButtonSaveEmpleado.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButtonSaveEmpleado.setText("GUARDAR");
        jButtonSaveEmpleado.setToolTipText("Guardas datos");
        jButtonSaveEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSaveEmpleadoMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonSaveEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, -1, 35));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel6.setText("EMPLEADO");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jLabelSalario.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jLabelSalario.setText("SALARIO");
        jPanel1.add(jLabelSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\SEBASTIAN MORENO\\Downloads\\Empleado.png")); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        jTextFieldSalario.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jTextFieldSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSalarioActionPerformed(evt);
            }
        });
        jTextFieldSalario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldSalarioKeyPressed(evt);
            }
        });
        jPanel1.add(jTextFieldSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 192, -1));

        jDateChooserEmpleado.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jPanel1.add(jDateChooserEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 192, -1));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jLabel2.setText("IDENTIFICACION");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jLabel8.setText("EDAD");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        jTextFieldId.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jTextFieldId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldId, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 192, -1));

        jTextFieldEdad.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jPanel1.add(jTextFieldEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 71, -1));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jLabel3.setText("FECHA INGRESO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel9.setText("NUEVO");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSaveEmpleadoMouseClicked
        if (JTextNombreEmpleado.getText().isBlank() || JTextNombreEmpleado.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Usted debe digitar el nombre");
            return;
        }
        
        if (jTextFieldId.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Ingrese una Identificacion");
            return;
        }
                
        try {
            int id = Integer.parseInt(jTextFieldId.getText());
            if (id > 999999999) {
                JOptionPane.showMessageDialog(null, "Identificacion no Valida");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingrese un valor numerico valido en Identificacion");
            return;
        }
        
        if (jTextFieldEdad.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Ingrese una Edad");
            return;
        }
        
        if (jComboBoxGenero.getSelectedItem().toString().startsWith("---")) {
            JOptionPane.showMessageDialog(null, "Seleccione un Genero");
            return;
        }
        
        if (jComboBoxCargo.getSelectedItem().toString().startsWith("---")) {
            JOptionPane.showMessageDialog(null, "Seleccione un Cargo");
            return;
        }
        
        if (jTextFieldSalario.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Ingrese un salario");
            return;
        }

        if (Integer.parseInt(jTextFieldSalario.getText()) < 1000000) {
            JOptionPane.showMessageDialog(null, "Ingrese un salario correcto");
            return;
        }
        
        if (jDateChooserEmpleado.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Ingrese la Fecha de Su Ingreso");
            return;
        }
        
       
        if (jTextFieldJefe.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Ingrese el Nombre del Jefe");
            return;
        }

        Empleado objEmpleado = new Empleado();
        objEmpleado.setNombre(JTextNombreEmpleado.getText());
        objEmpleado.setCargo(jComboBoxCargo.getSelectedItem().toString());
        objEmpleado.setIdentificacion(Integer.parseInt(jTextFieldId.getText()));
        objEmpleado.setGenero(jComboBoxGenero.getSelectedItem().toString());
        objEmpleado.setSalario(Double.parseDouble(jTextFieldSalario.getText()));
        
        Date fechaIngreso = jDateChooserEmpleado.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String fechaIngresoSring = sdf.format(fechaIngreso);
        objEmpleado.setFechaIngreso(fechaIngresoSring);
        objEmpleado.setNombreJefe(jTextFieldJefe.getText());
        objEmpleado.setEdad(Integer.parseInt(jTextFieldEdad.getText()));
        
        
        if(objEmpleado.existeEmpleado(objEmpleado.getIdentificacion())){
            JOptionPane.showMessageDialog(null, "El dato existe");
            return;
        }
        
        if(objEmpleado.almacenarDatosEmpleado(objEmpleado)){
            JOptionPane.showMessageDialog(null, "El Empleado fue Guardado");
            ClearScreen();
        }

    }//GEN-LAST:event_jButtonSaveEmpleadoMouseClicked
    
    public void ClearScreen(){
        JTextNombreEmpleado.setText("");
        jComboBoxCargo.setSelectedItem(0);
        jTextFieldId.setText("");
        jComboBoxGenero.setSelectedItem(0);
        jTextFieldSalario.setText("");
        jDateChooserEmpleado.setDate(null);
        jTextFieldJefe.setText("");
        jTextFieldEdad.setText("");
    }
    
    
    
    private void jButtonCloseEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseEmpleadoActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCloseEmpleadoActionPerformed

    private void jComboBoxGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxGeneroActionPerformed

    private void jTextFieldSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSalarioActionPerformed

    private void jTextFieldSalarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSalarioKeyPressed
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            jTextFieldSalario.setEditable(false);
        } else {
            jTextFieldSalario.setEditable(true);
        }
    }//GEN-LAST:event_jTextFieldSalarioKeyPressed

    private void jComboBoxCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCargoActionPerformed

    private void jTextFieldIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdActionPerformed

    }//GEN-LAST:event_jTextFieldIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpleadoInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpleadoInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpleadoInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpleadoInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new EmpleadoInterface().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTextNombreEmpleado;
    private javax.swing.JButton jButtonCloseEmpleado;
    private javax.swing.JButton jButtonSaveEmpleado;
    private javax.swing.JComboBox<String> jComboBoxCargo;
    private javax.swing.JComboBox<String> jComboBoxGenero;
    private com.toedter.calendar.JDateChooser jDateChooserEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCargo;
    private javax.swing.JLabel jLabelSalario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldEdad;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldJefe;
    private javax.swing.JTextField jTextFieldSalario;
    // End of variables declaration//GEN-END:variables
}
