package Interface;

import com.mycompany.trabajofinal1.ConsultaMedica;
import com.mycompany.trabajofinal1.HistoriaClinica;
import java.awt.Component;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author SEBASTIAN MORENO
 * @id: 1192792720
 * @fecha: 25/noviembre/2023
 */
public class HistoriaClinicaInterface extends javax.swing.JFrame {

    public HistoriaClinica objHistoriaClinica;
    public ConsultaMedica objConsultaMedica;
    public List<ConsultaMedica> consultas;

    /**
     * Creates new form HistoriaClinica
     */
    public HistoriaClinicaInterface() {
        initComponents();

        jTextAreaDatosHistoria.setLineWrap(true);
        jTextAreaDatosHistoria.setAlignmentX(Component.CENTER_ALIGNMENT);
        //jComboBoxFechaHistoria.addItemListener(this::jComboBoxFechaHistoriaItemStateChanged);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButtonNuevaConsulta = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDatosHistoria = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxFechaHistoria = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCedulaHistoria = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonFindHistoria = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\SEBASTIAN MORENO\\Downloads\\historia clinica.png")); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        jButtonNuevaConsulta.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButtonNuevaConsulta.setText("NUEVA CONSULTA");
        jButtonNuevaConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNuevaConsultaMouseClicked(evt);
            }
        });
        jPanel2.add(jButtonNuevaConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, -1, 35));

        jTextAreaDatosHistoria.setEditable(false);
        jTextAreaDatosHistoria.setBackground(new java.awt.Color(255, 255, 255));
        jTextAreaDatosHistoria.setColumns(20);
        jTextAreaDatosHistoria.setRows(5);
        jScrollPane2.setViewportView(jTextAreaDatosHistoria);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 364, 326));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel4.setText("DATOS HISTORIA CLINICA");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, -1));

        jComboBoxFechaHistoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxFechaHistoriaMouseClicked(evt);
            }
        });
        jPanel2.add(jComboBoxFechaHistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 147, 28));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel1.setText("HISTORIA CLINICA");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel5.setText("FECHA HISTORIA CLINICA");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        jTextFieldCedulaHistoria.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jPanel2.add(jTextFieldCedulaHistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 194, -1));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel2.setText("IDENTIFICACION");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        jButtonFindHistoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonFindHistoria.setIcon(new javax.swing.ImageIcon("C:\\Users\\SEBASTIAN MORENO\\Downloads\\find.png")); // NOI18N
        jButtonFindHistoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonFindHistoriaMouseClicked(evt);
            }
        });
        jPanel2.add(jButtonFindHistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));

        jButtonClose.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButtonClose.setText("CERRAR");
        jButtonClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCloseMouseClicked(evt);
            }
        });
        jPanel2.add(jButtonClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 550, -1, 35));
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 410, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 597, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_jButtonCloseMouseClicked

    private void jButtonNuevaConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNuevaConsultaMouseClicked
        clearScreen();
    }//GEN-LAST:event_jButtonNuevaConsultaMouseClicked

    private void jButtonFindHistoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFindHistoriaMouseClicked
        if (jTextFieldCedulaHistoria.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Ingrese Una Identificacion");
            return;
        }
        try {
            int id = Integer.parseInt(jTextFieldCedulaHistoria.getText());
            if (id > 999999999) {
                JOptionPane.showMessageDialog(null, "Identificacion No Valida");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingrese Un Valor Numerico Valido En La Identificacion");
            return;
        }

        HistoriaClinica objHistoriaClinica = new HistoriaClinica();

        try {
            String valorTexto = jTextFieldCedulaHistoria.getText();
            int textToInt = Integer.parseInt(valorTexto);
            consultas = objHistoriaClinica.getHistoriaPorPaciente(textToInt);
            for (ConsultaMedica objConsultaMedica : consultas) {
                jComboBoxFechaHistoria.addItem(objConsultaMedica.getFecha());
            }
            if (consultas == null) {
                JOptionPane.showMessageDialog(null, "Paciente No tiene Historias Clinicas");
                return;
            } else {
                
            }

        } catch (Exception e) {
        }

    }//GEN-LAST:event_jButtonFindHistoriaMouseClicked

    private void jComboBoxFechaHistoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxFechaHistoriaMouseClicked
        
        for (ConsultaMedica objConsulta : consultas) {
            if (objConsulta.getFecha().equals(jComboBoxFechaHistoria.getSelectedItem())) {
                jTextAreaDatosHistoria.setText(objConsulta.getDiagnostico()+"\n" + objConsulta.getTratamiento());
                //jTextAreaDatosHistoria.setText(objConsulta.getTratamiento());
            }
        }

    }//GEN-LAST:event_jComboBoxFechaHistoriaMouseClicked

    public String obtenerFecha(String fechaConsulta) {
        ConsultaMedica obConsultaMedica = new ConsultaMedica();
        int index = obConsultaMedica.getConsultaMedicas().indexOf(fechaConsulta);

        if (index != -1) {
            return obConsultaMedica.getConsultaMedicas().toString();
        } else {
            return "Historia clinica no encontrada";
        }
    }

    public void clearScreen() {
        jTextFieldCedulaHistoria.setText("");
        jComboBoxFechaHistoria.setSelectedItem(null);
        jTextAreaDatosHistoria.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistoriaClinicaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistoriaClinicaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistoriaClinicaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistoriaClinicaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new HistoriaClinicaInterface().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonFindHistoria;
    private javax.swing.JButton jButtonNuevaConsulta;
    private javax.swing.JComboBox<String> jComboBoxFechaHistoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaDatosHistoria;
    private javax.swing.JTextField jTextFieldCedulaHistoria;
    // End of variables declaration//GEN-END:variables
}
