package Interface;

/**
 *
 * @author SEBASTIAN MORENO
 * @id: 1192792720
 * @fecha: 25/noviembre/2023
 *
 */
public class MenuApp extends javax.swing.JFrame {


    public MenuApp() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Nit = new javax.swing.JLabel();
        Barrio = new javax.swing.JLabel();
        Direccion1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuEmpleados = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuMedicos = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuPaciente = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuCitasMedicas = new javax.swing.JMenu();
        jMenuHistoriaClinica = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\SEBASTIAN MORENO\\Downloads\\logo ok (1).png")); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\SEBASTIAN MORENO\\Downloads\\1.png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 640, 150));

        Nit.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        Nit.setForeground(new java.awt.Color(255, 0, 51));
        Nit.setText("NIT 1192792720");
        jPanel1.add(Nit, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        Barrio.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        Barrio.setForeground(new java.awt.Color(255, 0, 51));
        Barrio.setText("BARRIO CALI");
        jPanel1.add(Barrio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));

        Direccion1.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        Direccion1.setForeground(new java.awt.Color(255, 0, 51));
        Direccion1.setText("DIRECCION CRA 12 # 12 - 12");
        jPanel1.add(Direccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\SEBASTIAN MORENO\\Downloads\\banner.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\SEBASTIAN MORENO\\Downloads\\vertical.png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 80, 330));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\SEBASTIAN MORENO\\Downloads\\bg.jpeg")); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-790, 130, 1350, 250));

        menuBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBar.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        menuBar.setMinimumSize(new java.awt.Dimension(380, 230));
        menuBar.setName("Menu Opciones"); // NOI18N

        jMenu1.setText("EMPLEADOS");
        jMenu1.setToolTipText("Menu de opciones de empleados");
        jMenu1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N

        jMenuEmpleados.setText("NUEVO EMPLEADO");
        jMenuEmpleados.setToolTipText("Agregar un nuevo empleado");
        jMenuEmpleados.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jMenuEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuEmpleadosMouseClicked(evt);
            }
        });
        jMenu1.add(jMenuEmpleados);

        menuBar.add(jMenu1);

        jMenu6.setText("MENU MEDICO");
        jMenu6.setToolTipText("Contiene todo lo del medico");
        jMenu6.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N

        jMenuMedicos.setText("BONIFICACION MEDICO");
        jMenuMedicos.setToolTipText("Calcula si tiene bonificacion o no");
        jMenuMedicos.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jMenuMedicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuMedicosMouseClicked(evt);
            }
        });
        jMenu6.add(jMenuMedicos);

        jMenu5.setText("CONSULTA MEDICA");
        jMenu5.setToolTipText("Creado para que los medicos creen los datos de la consulta medica");
        jMenu5.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenu6.add(jMenu5);

        menuBar.add(jMenu6);

        jMenu4.setBackground(new java.awt.Color(204, 204, 255));
        jMenu4.setText("MENU PACIENTES");
        jMenu4.setToolTipText("Solo para pacientes");
        jMenu4.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N

        jMenuPaciente.setText("NUEVO PACIENTE");
        jMenuPaciente.setToolTipText("Crear un nuevo paciente");
        jMenuPaciente.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jMenuPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuPacienteMouseClicked(evt);
            }
        });
        jMenu4.add(jMenuPaciente);

        jMenu3.setText("CONSULTAS");
        jMenu3.setToolTipText("Opciones de consultas");
        jMenu3.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N

        jMenuCitasMedicas.setText("CITA MEDICA");
        jMenuCitasMedicas.setToolTipText("Agendar Cita medica");
        jMenuCitasMedicas.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jMenuCitasMedicas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuCitasMedicasMouseClicked(evt);
            }
        });
        jMenu3.add(jMenuCitasMedicas);

        jMenuHistoriaClinica.setText("HISTORIA CLINICA");
        jMenuHistoriaClinica.setToolTipText("Ver la historia clinica");
        jMenuHistoriaClinica.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jMenuHistoriaClinica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuHistoriaClinicaMouseClicked(evt);
            }
        });
        jMenu3.add(jMenuHistoriaClinica);

        jMenu4.add(jMenu3);

        menuBar.add(jMenu4);

        jMenu2.setText("SALIR");
        jMenu2.setToolTipText("Cerrar programa");
        jMenu2.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        menuBar.add(jMenu2);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuEmpleadosMouseClicked
        EmpleadoInterface formEmpleado = new EmpleadoInterface();
        
        formEmpleado.show();
        
    }//GEN-LAST:event_jMenuEmpleadosMouseClicked

    private void jMenuMedicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuMedicosMouseClicked
        MedicoInterface formInterface = new MedicoInterface();
        
        formInterface.show();
    }//GEN-LAST:event_jMenuMedicosMouseClicked

    private void jMenuPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuPacienteMouseClicked
        PacienteInterface formPacienteInterface = new PacienteInterface();
        
        formPacienteInterface.show();
    }//GEN-LAST:event_jMenuPacienteMouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        this.dispose();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenuCitasMedicasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuCitasMedicasMouseClicked
        CitaInterface formCitaInterface = new CitaInterface();
        
        formCitaInterface.show();
    }//GEN-LAST:event_jMenuCitasMedicasMouseClicked

    private void jMenuHistoriaClinicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuHistoriaClinicaMouseClicked
        HistoriaClinicaInterface formHistoriaClinicaInterface = new HistoriaClinicaInterface();
        
        formHistoriaClinicaInterface.show();
    }//GEN-LAST:event_jMenuHistoriaClinicaMouseClicked

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        ConsultaMedicaInterface formConsultaMedicaInterface = new ConsultaMedicaInterface();
        
        formConsultaMedicaInterface.show();
    }//GEN-LAST:event_jMenu5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MenuApp().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Barrio;
    private javax.swing.JLabel Direccion1;
    private javax.swing.JLabel Nit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenuCitasMedicas;
    private javax.swing.JMenu jMenuEmpleados;
    private javax.swing.JMenu jMenuHistoriaClinica;
    private javax.swing.JMenu jMenuMedicos;
    private javax.swing.JMenu jMenuPaciente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
